name: Publish Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: docker # The environment this jobs runs in

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }} # Acess secret from the 'docker' environment
        password: ${{ secrets.DOCKERHUB_PASSWORD }} # Acess secret from the 'docker' environment

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: aktagon/ollama-html-ui:latest
