name: Run Tests

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.yarn
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install

    - name: Install Playwright
      run: yarn playwright install

    - name: Run tests
      run: |
        nohup yarn parcel index.html > server.log 2>&1 &
        # Run server in the background
        # nohup yarn server > server.log 2>&1 &
        # Wait for the server to start
        sleep 10
        export GITHUB_ACTIONS=true
        yarn test
        yarn test:mobile

    - name: Upload server log
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: server-log
        path: server.log
